name: CI on Windows

on: [push, pull_request]

jobs:
  Build-And-Test-Windows:
    runs-on: windows-latest
    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build Compiler
      run: dotnet build --configuration Release
    - name: Test Compiler
      run: dotnet test --configuration Release
